version: 2
snapshot:
  widths:
    - 375
    - 768
    - 1280
  min-height: 800
  percy-css: |
    html {
      scroll-behavior: auto !important;
    }
storybook:
  build-dir: storybook-static
  delay: 500
