version: '3.8'

services:
  # Frontend - Next.js 14
  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    container_name: eldercare_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - eldercare_network
    restart: unless-stopped

  # Backend - Laravel 12
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: eldercare_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=eldercare_db
      - DB_USERNAME=eldercare_admin
      - DB_PASSWORD=your_secure_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - eldercare_network
    restart: unless-stopped
    command: php artisan serve --host=0.0.0.0 --port=8000

  # Nginx - Web Server
  nginx:
    image: nginx:alpine
    container_name: eldercare_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - eldercare_network
    restart: unless-stopped

  # MySQL 8.0
  mysql:
    image: mariadb:10.11
    container_name: eldercare_mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=Admin1234
      - MYSQL_DATABASE=eldercare_db
      - MYSQL_USER=eldercare_admin
      - MYSQL_PASSWORD=your_secure_password
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - eldercare_network
    restart: unless-stopped

  # Redis 7
  redis:
    image: redis:7-alpine
    container_name: eldercare_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - eldercare_network
    restart: unless-stopped

  # MeiliSearch
  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: eldercare_meilisearch
    ports:
      - "7700:7700"
    volumes:
      - meilisearch_data:/meili_data
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=masterKey_dev_only_change_in_production
    networks:
      - eldercare_network
    restart: unless-stopped

  # Mailhog (Email testing)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: eldercare_mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    networks:
      - eldercare_network
    restart: unless-stopped

networks:
  eldercare_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  meilisearch_data:
    driver: local
