name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Run linting
      run: |
        cd frontend
        npm run lint

    - name: Run type checking
      run: |
        cd frontend
        npm run type-check

    - name: Run unit tests
      run: |
        cd frontend
        npm run test:coverage

    - name: Install Playwright browsers for Storybook tests
      run: |
        cd frontend
        npx playwright install --with-deps chromium

    - name: Run Storybook interaction tests
      env:
        STORYBOOK_DISABLE_TELEMETRY: '1'
        NEXT_TELEMETRY_DISABLED: '1'
      run: |
        cd frontend
        npm run storybook:test

    - name: Capture Percy Storybook snapshots
      if: ${{ secrets.PERCY_TOKEN != '' }}
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        STORYBOOK_DISABLE_TELEMETRY: '1'
        NEXT_TELEMETRY_DISABLED: '1'
      run: |
        cd frontend
        npm install --prefer-offline
        npm run percy:storybook

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./frontend/coverage
        flags: frontend
        name: frontend-coverage

    - name: Build application
      run: |
        cd frontend
        npm run build

    - name: Run E2E tests
      run: |
        cd frontend
        npm run test:e2e

  test-backend:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: eldercare_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:6-alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: bcmath, gd, imagick, intl, pdo, sqlite, pdo_mysql, mbstring, xml, zip, pcntl
        coverage: xdebug

    - name: Copy environment file
      run: |
        cd backend
        cp .env.example .env
        php artisan key:generate

    - name: Install dependencies
      run: |
        cd backend
        composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Run migrations
      run: |
        cd backend
        php artisan migrate --force

    - name: Run tests
      run: |
        cd backend
        vendor/bin/phpunit --coverage-clover=coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./backend
        flags: backend
        name: backend-coverage

  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Build application
      run: |
        cd frontend
        npm run build

    - name: Run Lighthouse CI
      run: |
        cd frontend
        npm install -g @lhci/cli@0.12.x
        lhci autorun
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  accessibility:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Build application
      run: |
        cd frontend
        npm run build

    - name: Run accessibility tests
      run: |
        cd frontend
        npm install -g pa11y-ci
        npm run start &
        sleep 10
        pa11y-ci --sitemap http://localhost:3000/sitemap.xml --sitemap-exclude "/pdf/"
